# Generated by Django 5.1.5 on 2025-01-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_cooking_recipe_cost_recipe_difficult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_preparation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(),
        ),
    ]
