# Generated by Django 5.1.5 on 2025-02-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_time_preparation_alter_recipe_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_of_measure',
            field=models.CharField(choices=[('g', 'Grammi'), ('kg', 'Kilogrammi'), ('ml', 'Millilitri'), ('l', 'Litri'), ('pz', 'Pezzi'), ('cup', 'Tazze'), ('tbsp', 'Cucchiai'), ('tsp', 'Cucchiaini')], max_length=255),
        ),
    ]
